
services:
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: boraszat
    ports:
      - "3306:3306"
    volumes:
      # Ha FEJLESZTÉS alatt állandóan frissíteni akarod az adatokat, 
      # érdemes lehet kivenni a db_data-t, vagy mindig down -v-vel indítani.
      - db_data:/var/lib/mysql 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # Fontos: Adjunk neki egy kis időt az induláshoz
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysqldb
      PMA_USER: root
      PMA_PASSWORD: ""
      PMA_ARBITRARY: 1
    depends_on:
      mysqldb:
        condition: service_healthy # Megvárja, amíg a MySQL tényleg kész van

  api:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysqldb
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: boraszat
    depends_on:
      - mysqldb
    # ÚJ: Ez teszi lehetővé, hogy a server.js módosítása azonnal hasson
    command: node server.js
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  client:
    build: ./frontend/fooldal
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - api
    # ÚJ: Ez teszi lehetővé, hogy a React fájlok módosítása azonnal látsszon a böngészőben
    volumes:
      - ./frontend/fooldal:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db_data: